stages:
  - test_back
  - container
  - deploy_back
  - test_front
  - build
  - deploy
  - test_postman


jobs_desarrollo_tests_back:
  stage: test_back
  script: 
      - cd ./backend
      - pwd
      - echo "Maven test started"
      - mvn clean test
  only:
    - desarrollo 


jobs_desarrollo_container_back:
  image: 
    name: amazon/aws-cli:latest
    entrypoint: [""]
  stage: container
  variables: 
    DOCKER_REGISTRY: 145504712931.dkr.ecr.us-east-1.amazonaws.com 
    APP_NAME: g1-sixvago
  services:
    - docker:dind
  before_script:
    - cd ./backend
    - export TAG=${CI_COMMIT_SHORT_SHA}-${CI_JOB_ID}
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $DOCKER_REGISTRY
  script: 
    - echo "Docker build started"
    - docker build -t $DOCKER_REGISTRY/$APP_NAME:$TAG --build-arg USERNAME=${USERNAME} --build-arg PASSWORD=${PASSWORD} --build-arg SECRET_KEY=${SECRET_KEY} .   
    - docker push $DOCKER_REGISTRY/$APP_NAME:$TAG
    - docker tag $DOCKER_REGISTRY/$APP_NAME:$TAG $DOCKER_REGISTRY/$APP_NAME:latest
    - docker push $DOCKER_REGISTRY/$APP_NAME:latest
  only:
    - desarrollo


jobs_deploy_back_ec2: 
  stage: deploy_back
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:    
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$EC2_IPADDRESS "sudo docker kill $(docker ps -q) || sudo docker rm $(docker ps -a -q) || sudo docker rmi $(docker images -q) || sudo docker run -d -p 8080:8080 --env USERNAME=${USERNAME} --env PASSWORD=${PASSWORD} --env SECRET_KEY=${SECRET_KEY} 145504712931.dkr.ecr.us-east-1.amazonaws.com/g1-sixvago:latest"
  only:
    - desarrollo

# jobs_tests_front:
#   image: node:16
#   stage: test_front
#   script: 
#     - cd ./Frontend
#     - npm install
#     - cd ./src
#     - pwd
#     - npm test
#   only:
#     - desarrollo 

jobs_build_front:
  image: node:16.15.1 #node:10
  stage: build  
  script:
    - cd ./Frontend
    - npm install
    - npm run build
  artifacts:
    when: always
    paths:
      - ./Frontend/build/
  only:
    - desarrollo


jobs_deploy_front_s3:
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  dependencies:
    - jobs_build_front
  stage: deploy
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp ./Frontend/build/ s3://$S3_BUCKET --recursive
  when: manual
  only:
    - desarrollo


test_job_postman:
  stage: test_postman
  image: 
    name: postman/newman_alpine33    
    entrypoint: [""]
  script:
    - newman --version
    - npm config set unsafe-perm true
    - npm install -g newman-reporter-html 
    - newman run proyecto_integrador.postman_collection.json --globals usen_esto.postman_environment.json  --reporters cli,html,junit --reporter-html-export  report.html --reporter-junit-export  report.xml
  artifacts:
    when: always
    paths:
      - report.html
    reports:
      junit: report.xml
  when: manual
  only:
    - desarrollo
    