stages:
  - test
  - build
  - container
  - deploy


# jobs_tests_front:
#   image: node:12.20.0
#   stage: test
#   script: 
#     - cd ./Frontend
#     - npm install
#     - cd ./src
#     - pwd
#     - npm test
#   only:
#     - desarrollo 


# jobs_desarrollo_tests_back:
#   stage: test
#   script: 
#       - cd ./backend
#       - pwd
#       - echo "Maven test started"
#       - mvn clean test
#   only:
#     - desarrollo 


# test_job_postman:
#   stage: test
#   image: 
#     name: postman/newman_alpine33    
#     entrypoint: [""]

#   script:
#     - newman --version
#     - npm config set unsafe-perm true
#     - npm install -g newman-reporter-html 
#     - newman run proyecto_integrador.postman_collection.json --globals usen_esto.postman_environment.json  --reporters cli,html,junit --reporter-html-export  report.html --reporter-junit-export  report.xml
#   artifacts:
#     when: always
#     paths:
#       - report.html
#     reports:
#       junit: report.xml
#   when: manual
#   only:
#     - desarrollo

jobs_desarrollo_container_back:
  image: docker:latest
  stage: container
  services:
    - docker:dind
  before_script:
    - cd ./backend
    - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin 145504712931.dkr.ecr.us-east-1.amazonaws.com
  script: 
    - echo "Docker build started"
    - docker build -t g1-sixvago .
    - docker tag g1-sixvago:latest 145504712931.dkr.ecr.us-east-1.amazonaws.com/g1-sixvago:latest
    - docker push 145504712931.dkr.ecr.us-east-1.amazonaws.com/g1-sixvago:latest
  when: manual
  only:
    - desarrollo